### ISSUE TITLE
Feature Requests 

### ISSUE THREAD

**Issue by martham93** [DigitalGlobe/pyveda#3]
Hello. A few feature requests per my call with @chelm and working with the tent data in Veda. It's been really cool to work with so far thank you!! I think these could be really helpful for us all and other future users 

- [ ] Documentation, especially with what can be done with an object created by the `.batch` function, especially `data.train` vs. `data.test` and `data.train.images`,  `data.train.classificaion` 

- [ ] default `to_cache = True` for `.batch` function 

- [ ] built in methods to tell a user the count and indexes of items in each class of a classification dataset or how many positive/negative samples and indexes in the case of binary data

**Comment by martham93** [comment]
this is what I've been doing for the tent data to find positive/negative samples, but it's probably not the best solution. 

```
pos_indx = []
neg_indx = []
for i in range(len(data.train)): 
    if data.train.classification[i] == 1:
        pos_indx.append(i)
    else:
        neg_indx.append(i)
```

**Comment by rjpolackwich** [comment]
I think a lot of these issues have been covered and stem from the project being quite young, so I'm going to go ahead and close this (cc @martham93 @chelm). That said, this forum is a great place for deatiled FRs, Bug reports, etc, and I'd encourage us core Veda devs should take advantage of it going forward.
